name = "Languages"
uuid = "d30315cb-68a7-4c14-9e7e-43d1cd3d2c72"
authors = ["John Myles White, Avik Sengupta and other contributors."]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
JSON = "0.19.0, 0.21.0"
julia = "0.7, 1"
